### ISSUE TITLE
How to integrate with lazy to lazy load based on keymaps?

### ISSUE THREAD

**Issue by khalidchawtany** [clvnkhr/macaltkey.nvim#1]
Is there any way that we can integrate it with Lazy to enable lazy loaded key maps?

In the following example I want `<a-a>` to load telescope-tabs plugin and then run the function.
```
{
  "LukasPietzschmann/telescope-tabs",
  dependencies = {"nvim-telescope/telescope.nvim"},
  keys = {
    {  "<a-t>",  function() require("telescope").extensions["telescope-tabs"].list_tabs() end }
  },
  config = true
}       
```

**Comment by clvnkhr** [comment]
Hm, I didn't consider this. Can you try to ensure macaltkey is setup before this,  then replace `"<a-t>"` with `require"macaltkey".convert("<a-t>")`?

**Comment by khalidchawtany** [comment]
It did not work. I had to go around lazy to load the macaltkey plugin. I can see that lazy lists the alt keys to lazy load the plugins. However, the keys does not trigger the action.

Update:
----------------
I was wrong. It does work if you call setup after loading the plugin manually.
